### ISSUE TITLE
你好，我想问一下对于VOT数据集你是咋进行评测的呀

### ISSUE THREAD

**Issue by dlivxpr** [Giveupfree/SiamFDB#3]
pysot对于VOT2016、VOT2018支持良好，但是VOT2019一直有问题，测试正常，但是评估报错。我看你的项目里面有test_vot.py,这个是咋使用的呀，找不到指定VOT数据集的位置

**Comment by Giveupfree** [comment]
pysot对于vot2019测评存在一个bug，这个bug已经在我的另一个git项目上做了修复处理https://github.com/Giveupfree/SOTDrawRect
